name: aqua_sense
description: IoT Water Level Monitoring App
publish_to: 'none' # Private package, won't be published

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  cloud_firestore: ^4.13.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Add assets or fonts here if needed
  # assets:
  #   - images/example.png
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf